name: Generate Butterfly
'on':
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Butterfly
        uses: Platane/snk@master
        id: generate-butterfly
        with:
          github_user_name: johnitopaisah
          gif_out_path: dist/github-contribution-grid-butterflies.gif
          svg_out_path: dist/github-contribution-grid-butterflies.svg
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: output
          force: true
