name: Generate ButterFly

'on':
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable automatic credentials to use PAT

      - name: Generate Butterfly SVG
        uses: Platane/snk@master
        with:
          github_user_name: johnitopaisah
          svg_out_path: dist/github-contribution-grid-butterflies.svg

      - name: Set up Git user
        run: |
          git config user.name "johnitopaisah"
          git config user.email "johnitopa.isah@gmail.com"

      - name: Commit and Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}  # No single quotes, ensure correct reference
          branch: output
          force: true
