name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Generates the snake GIF and SVG
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: johnitopaisah
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Set outputs using environment files (if needed)
      - name: Set output using environment files
        run: echo "my_output=value" >> $GITHUB_ENV

      # Push the generated snake files to the output branch
      - name: Push Snake to Output Branch
        uses: ad-m/github-push-action@v0.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # Deploy the content to GitHub Pages
      - name: Deploy Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
