name: Generate Snake File
'on':
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: johnitopaisah
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Set up Git user
        run: |
          git config user.name "johnitopaisah"
          git config user.email "johnitopa.isah@gmail.com"
      - name: Commit and Push changes
        uses: ad-m/github-push-action@v0.6.1
        with:
          github_token: '${{ secrets.GH_PAT }}'
          branch: output
          force: true
      - name: Deploy Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: '${{ secrets.GH_PAT }}'
