name: Generate_Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable automatic credentials to use PAT

      # Generate the Butterfly SVG
      - name: Generate Butterfly SVG
        uses: Platane/snk@master
        with:
          github_user_name: johnitopaisah
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
        # Check if the SVG is generated (debug step)
      - name: List the files in the dist folder
        run: ls -al dist

      # Set up Git user
      - name: Set up Git user
        run: |
          git config user.name "johnitopaisah"
          git config user.email "johnitopaisah@gmail.com"
      # Commit and Push changes
      - name: Commit and Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}  # Make sure you are using the correct secret
          branch: output
          force: true
